language: dart
dist: precise
dart:
  - "1.24.2"
addons:
  firefox: "latest"
before_install:
  - export DISPLAY=:99.0
  - export PATH=$PATH":$PWD"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - pub run dart_dev analyze
  - pub run dependency_validator -i browser
  - pub run dart_dev test
