name: resize_observer_polyfill_wrapper
description: A Dart wrapper for the `resize-observer-polyfill` JS library.
version: 1.0.0
homepage: https://github.com/JaceHensley/resize_observer_polyfill_wrapper
author: Jace Hensley <jacehensley@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.1
  meta: ^1.1.2

dev_dependencies:
  browser: ^0.10.0+2
  dart_dev: ^1.8.0
  dart_to_js_script_rewriter: ^1.0.1
  dependency_validator: ^1.0.0
  test: ^0.12.29

transformers:
- dart_to_js_script_rewriter
